name: The PHENIX website
description: The website of the PHENIX Experiment at RHIC (Brookhaven National Laboratory)
url: http://phenix.org

excerpt_separator: <!--more-->
timezone: America/New_York
highlighter: rouge

markdown: kramdown
future: true
exclude: [vendor]


###############################################################
# !!! Important as we are not serving from the top folder !!! #
baseurl: /web
###############################################################

# To simplify references to GitHub:
github: "https://github.com/PhenixCollaboration/web"

# Various formatting aids:
tablepadding: "&nbsp;&nbsp;&nbsp;"
navbarpadding_left: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
navbarpadding_right: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"

# Custom helper variables:
blank: 'target="_blank"'

# Logo:
phenix_logo: /images/logos/phenix_logo_centered.png

hr: '<hr style="height:1px;border-width:0;color:royalblue;background-color:royalblue"/>'

# Icons:
home_icon: /images/icons/house-24.png
test_icon: /images/icons/test-tube-5-32.png
collaboration_icon: /images/icons/geography-32.png
experiment_icon: /images/icons/atomic-24.png
detectors_icon: /images/icons/cog-24.png
software_icon: /images/icons/console-24.png
#analysis_icon: /images/icons/puzzle-2-24.png
analysis_icon: /images/icons/research-32.png
results_icon: /images/icons/checked-checkbox-32.png
resources_icon: /images/icons/literature-24.png
#about_icon: /images/icons/question-mark-5-32.png
about_icon: /images/icons/info-2-32.png
thumbs_icon: /images/icons/thumbs-up-32.gif
dn_arrow_icon: /images/icons/arrow-216-32.png

# Badges
zenodo_badges: /images/badges/zenodo/

# Used in site upgrades:
navbar: 'new'

# Assets steering
document_folder: '/assets/documents/'
ert_mask_folder: '/assets/trigger/ert/'

# URLs
zenodo_prefix: 'https://doi.org/10.5281/zenodo.'


exclude: [_data/db, scripts, attic.txt, utils, Gemfile, LICENSE, ./test, README.md, ]

lumi: 'no'

###
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
collections:
  test:
    output: true
    permalink: /test/:title.html
  collaboration:
    output: true
    permalink: /collaboration/:title.html
  experiment:
    output: true
    permalink: /experiment/:title.html
  runs:
    output: true
    permalink: /runs/:title.html
  lumi:
    output: true
    permalink: /lumi/:title.html
  detectors:
    output: true
    permalink: /detectors/:title.html
  software:
    output: true
    permalink: /software/:title.html
  analysis:
    output: true
    permalink: /analysis/:title.html
  results:
    output: true
    permalink: /results/:title.html
  resources:
    output: true
    permalink: /resources/:title.html
  about:
    output: true
    permalink: /about/:title.html
