name: The PHENIX website
description: The website of the PHENIX Experiment at RHIC (Brookhaven National Laboratory)
url: http://phenix.org

excerpt_separator: <!--more-->
timezone: America/New_York
highlighter: rouge

markdown: kramdown
future: true
exclude: [vendor]

# !!! Important as we are not serving from the top folder !!!
baseurl: /web

# To simplify references to GitHub:
github: "https://github.com/PhenixCollaboration/web"

# Various formatting aids:
tablepadding: "&nbsp;&nbsp;&nbsp;"

# Used in site upgrades:
navbar: 'new'

# Assets steering
document_folder: '/assets/documents/'
ert_mask_folder: '/assets/trigger/ert/'

###
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from
collections:
  activities:
    output: true
    permalink: /activities/:title.html
  experiment:
    output: true
    permalink: /experiment/:title.html
  runs:
    output: true
    permalink: /runs/:title.html
  lumi:
    output: true
    permalink: /lumi/:title.html
  detectors:
    output: true
    permalink: /detectors/:title.html
  software:
    output: true
    permalink: /software/:title.html
  about:
    output: true
    permalink: /about/:title.html
  analysis:
    output: true
    permalink: /about/:title.html
  resources:
    output: true
    permalink: /resources/:title.html
  people:
    output: true
    permalink: /people/:title.html
