---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: _resources
  label: Resources
  create: all
  match: "**/*"
- type: directory
  path: _analysis
  label: Analysis
  create: all
  match: "**/*"
- type: directory
  path: _software
  label: Software
  create: all
  match: "**/*"
- type: directory
  path: _detectors
  label: Detectors
  create: all
  match: "**/*"
- type: directory
  path: _lumi
  label: Lumi
  create: all
  match: "**/*"
- type: directory
  path: _runs
  label: Runs
  create: all
  match: "**/*"
- type: directory
  path: _experiment
  label: Experiment
  create: all
  match: "**/*"
- type: directory
  path: _collaboration
  label: Collaboration
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
